name: PerchShopFinder
version: 1.0.0
main: me.perch.shopfinder.FindItemAddOn
api-version: 1.20
authors: [ KayaLambrex ]
softdepend:
  - QuickShop
  - QuickShop-Hikari
  - PlayerWarps
  - WorldGuard
  - Essentials
  - ProtocolLib
  - PlaceholderAPI
  - Vault

permissions:
  finditem.use:
    description: Enables players to use the /finditem command
    default: true
  finditem.hideshop:
    description: Enables players to use the /finditem hideshop & /finditem revealshop
    default: true
  finditem.reload:
    description: For OP. Enables use of '/finditemadmin reload' to reload the config
    default: op
  finditem.admin:
    description: For OP. Enables use of all admin commands
    default: op
  finditem.shoptp:
    description: If 'allow-direct-shop-tp' is enabled in config, players require this permission to be able to teleport
    default: op
  finditem.shoptp.own:
    description: Allows teleporting to own shops
    default: true
  finditem.shoptp-delay.bypass:
    description: Bypass the TP delay for teleporting to shop
    default: op
  finditem.shoptp.bypass-safetycheck:
    description: Bypass safe location check when teleporting to the shop
    default: false
commands:
  wheretobuy:
    description: Find where to buy an item
    usage: /wheretobuy <item/hand>
    permission: finditemaddon.wtb
    aliases: [wtb]
  wheretosell:
    description: Find where to sell an item
    usage: /wheretosell <item/hand>
    permission: finditemaddon.wts
    aliases: [ wts ]
  outofstock:
    description: Shows your out-of-stock shops
    usage: /outofstock
    permission: finditemaddon.oos
    aliases: [ oos ]
  excludewarp:
    description: Exclude your warp from all wtb searches
    usage: /excludewarp <warpname>
  includewarp:
    description: Include your warp in all wtb searches
    usage: /includewarp <warpname>
  highlightcolour:
    description: Set your shop highlight colour
    usage: /highlightcolour <colour>
  wheretoget:
    description: Highlights nearby shops selling an item
    usage: /wheretoget <item>
    aliases: [ wtg ]